# Generated by Django 4.0.3 on 2022-04-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ('-publish',), 'ordering': ('-publish',)},
        ),
    ]
