# Generated by Django 4.0.1 on 2022-02-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintro',
            name='avatar',
            field=models.ImageField(height_field=260, upload_to='images'),
        ),
    ]
