# Generated by Django 4.0.1 on 2022-02-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_userintro_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintro',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
