name: Django CI SFTP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "SFTP"
  deploy-via-sftp:
  # build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9.*"]

    steps:
    - uses: actions/checkout@v2
          
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
          username: coglescode
          server: coglescode.com
          port: 38504 
          # ${{ secrets.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # will put all file under this path
          local_path: ./* # default is ./*           
          # files will copy to under remote_path
          remote_path: /home/coglescode/coglescode_com          
          
          # sftp args
          args: '-o ConnectTimeout=5'

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
       
    #- name: Run Tests
    #  run: |
    #    python manage.py test
    #- name: Collect Static
    #  run: |
    #    python manage.py collectstatic --noinput
    
